// GENERATED by `npm run english-names:fetch` (scripts/english-names-fetch.ts) —
// DO NOT HAND-EDIT. Every entry here was read directly off CBS's own public
// English (ENG) sibling tables (ADR 058, Task 3 Fix round 1) — a Dutch
// string that CBS itself never gave a matching English form for, or that
// CBS's own words genuinely disagree on across two reachable contexts (rule
// 3 — a conflict), is never written here; it is hand-curated instead in the
// sibling src/registry/english-names.data.ts, which composes its exported
// maps as `{ ...CBS_X, ...HAND_X }`. Re-run the fetch script to regenerate
// this file after a registry change (a new canonical measure, a new
// alternate, a new default coordinate) — hand edits here are silently
// overwritten on the next run and never reviewed as "the CBS source of
// truth" again.
//
// Pure data, no functions, no imports — same "table module" contract as
// english-names.data.ts (see that file's header): importable from anywhere,
// including the web client bundle, without pulling in any logic.

export const CBS_MEASURE_TITLES: Record<string, string> = {
  "Bruto binnenlands product": "Gross domestic product",
  "Bruto elektriciteitsproductie": "Gross production of electricity",
  "Consumentenvertrouwen": "Consumer confidence",
  "CPI": "CPI",
  "Doorvoerwaarde inkomend": "Inbound transit value",
  "Economisch klimaat": "Economic climate",
  "Gemiddelde verkoopprijs": "Average purchase price",
  "Indexcijfer": "Indices",
  "Jaarmutatie CPI": "Annual rate of change CPI",
  "Jaarmutatie invoerwaarde": "Annual change in import value",
  "Jaarmutatie PPI": "Year-on-year development",
  "Jaarmutatie uitvoerwaarde": "Annual change in export value",
  "Kalendergecorrigeerd": "Calendar adjusted production/turnover",
  "Koopbereidheid": "Willingness to buy",
  "Niet-seizoengecorrigeerd": "Not seasonally adjusted",
  "Ongecorrigeerd": "Uncorrected production/turnover",
  "Ontwikkeling t.o.v. een jaar eerder": "Changes compared to one year earlier",
  "Producentenprijsindex (PPI)": "Price index numbers excluding excise",
  "Seizoengecorrigeerd": "Seasonally adjusted",
  "Totale invoerwaarde": "Total import value",
  "Totale uitvoerwaarde": "Total export value",
  "Uitgesproken faillissementen": "Pronounced bankruptcies",
  "Verkochte woningen": "Number of dwellings sold",
  "Volumemutaties": "Volume changes",
  "Volumemutaties, koopdaggecorrigeerd": "Volume changes shoppingday adjusted",
  "Wederuitvoerwaarde": "Re-export value",
};

export const CBS_TABLE_TITLES: Record<string, string> = {
  "Arbeidsdeelname en werkloosheid per maand": "Monthly labour participation and unemployment",
  "Bbp, productie en bestedingen; kwartalen, mutaties, nationale rekeningen": "GDP, output and expenditures; changes, Quarterly National Accounts",
  "Bestaande koopwoningen; gemiddelde verkoopprijzen, regio": "Existing own homes; average purchase prices, region",
  "Bestaande koopwoningen; verkoopprijzen prijsindex 2020=100": "Existing own homes; purchase prices, price indices 2020=100",
  "Bestaande koopwoningen; verkoopprijzen, prijsindex 2020=100, regio": "Existing own homes; purchase prices, price index 2020=100, region",
  "Consumentenprijzen; CPI 2025=100, index en mutaties": "Consumer prices; CPI 2025=100, index and rates of change",
  "Consumentenvertrouwen, economisch klimaat en koopbereidheid; gecorrigeerd": "Consumer confidence, economic climate and willingness to buy",
  "Consumptieve bestedingen door huishoudens; nationale rekeningen, 2021=100": "Consumption expenditure of households; National accounts, 2021=100",
  "Faillissementen; kerncijfers": "Bankruptcies; key figures",
  "Handel en diensten; omzet- en productieontwikkeling, index 2021=100": "Trade and services; turnover and production changes, index 2021=100",
  "Hernieuwbare elektriciteit; productie en vermogen": "Renewable electricity; production and capacity",
  "Internationale goederenhandel; grensoverschrijding, kerncijfers": "International trade in goods; border crossing, key figures",
  "Producentenprijzen (PPI); afzet-, invoer-, verbruiksprijzen, index 2021=100": "Producer Price Index (PPI); output and importprices by product, 2021=100",
};

export const CBS_DIM_LABELS: Record<string, string> = {
  "000000 Alle bestedingen": "000000 All items",
  "15 tot 25 jaar": "15 to 24 years",
  "15 tot 75 jaar": "15 to 74 years",
  "25 tot 45 jaar": "25 to 44 years",
  "45 tot 75 jaar": "45 to 74 years",
  "47 Detailhandel (niet in auto's)": "47 Retail trade (not in motor vehicles)",
  "471 Supermarkten en warenhuizen": "471 Non-specialised retail sales.",
  "B-E Nijverheid (geen bouw) en energie": "B-E Industry (except construction)",
  "Bedrijven en instellingen": "Companies and institutions",
  "Binnenlandse consumptie huishoudens": "Domestic consumption by households",
  "Invoerprijzen": "Consumption of foreign products",
  "Totaal afzetprijzen": "Total sales",
  "Totaal goederen": "Total goods",
  "Totaal landen": "Total countries",
  "Totaal rechtsvormen Nederland/buitenland": "Total legal forms all nationalities",
  "Volume, t.o.v. voorgaande periode": "Volume, on previous period (q/q)",
  "Volume, t.o.v. zelfde periode vorig jaar": "Volume, on corresponding period (y/y)",
  "Waarde, t.o.v. zelfde periode vorig jaar": "Value, on corresponding period (y/y)",
  "Zonnestroom": "Solar photovoltaic",
};

export const CBS_REGIONS: Record<string, string> = {
  "Nederland": "The Netherlands",
};
